# the compiler: g++ for C++
CC = g++

# compiler flags:
# 	-g    adds debugging information to the executable file
# 	-Wall turn on most, but not all, compiler wartnings
CFLAGS = -g -Wall

TARGET = zad1 zad2 zad3 zad4 zad5 zad6 zad7 zad8 zad9 zad10

all: $(TARGET)

zad1: zad1.cpp
	$(CC) zad1.cpp $(CFLAGS) -o zad1_main

zad2: zad2.cpp
	$(CC) zad2.cpp $(CFLAGS) -o zad2_main

zad3: zad3.cpp
	$(CC) zad3.cpp $(CFLAGS) -o zad3_main

zad4: zad4.cpp
	$(CC) zad4.cpp $(CFLAGS) -o zad4_main

zad5: zad5.cpp
	$(CC) zad5.cpp $(CFLAGS) -o zad5_main

zad6: zad6.cpp
	$(CC) zad6.cpp $(CFLAGS) -o zad6_main

zad7: zad7.cpp
	$(CC) zad7.cpp $(CFLAGS) -o zad7_main

zad8: zad8.cpp
	$(CC) zad8.cpp $(CFLAGS) -o zad8_main

zad9: zad9.cpp
	$(CC) zad9.cpp $(CFLAGS) -o zad9_main

zad10: zad10.cpp
	$(CC) zad10.cpp $(CFLAGS) -o zad10_main

clean:
	rm *_main
